### PR TITLE
OOP school library: add Person, Student and Teacher classes

### PR DESCRIPTION
**Pull request by fabgrel10**
In this PR:

- [x] Create class Person with specifications.
- [x] Create class Student with specifications.
- [x] Create class Teacher with specifications.
- [x] Create main file to run the app.

### CODE REVIEW

**Comment by omar-labana** [comment]
@fabgrel10 really nice commit history

**Comment by fabgrel10** [comment]
> @fabgrel10 really nice commit history

Thank you for your comments @omar-labana, I appreciate it.

**Review by omar-labana — APPROVED** [review]
# **Approved ✔️**

Hi @fabgrel10,

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by fabgrel10** [comment]
Thank you for the review @omar-labana!

**Pull request merged**
